AWSTemplateFormatVersion : '2010-09-09'
Description: CDFA DCSS serverless application.
Parameters:
  Environment:
    Type: String
  HashKey:
    Type: String

Resources:

###################################### LAMBDA FUNCTIONS ################################################################

  #DELINQUENCY IMPORT

  DelinquencyImportFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub dcss-${Environment}-delinquency-import-func
      Handler: src/import/delinquency-import.handler
      Runtime: nodejs6.10
      Code: ./
      Role: !GetAtt DelinquencyImportFunctionRole.Arn
      KmsKeyArn: !GetAtt DCSSDataKMSKey.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DcssTable
          KEY_ALIAS: !Ref DCSSDataKMSKeyAlias
          HASH_KEY: !Sub ${HashKey}

  DelinquencyImportFunctionS3Permission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt DelinquencyImportFunction.Arn
        Principal: s3.amazonaws.com
        SourceAccount: !Ref AWS::AccountId
        SourceArn: !Sub arn:aws:s3:::dcss-${Environment}-delinquency-import-bucket

  #STATUS

  StatusAPIFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub dcss-${Environment}-status-func
      Handler: src/api/status.handler
      Runtime: nodejs6.10
      Code: ./
      Role: !GetAtt StatusAPIFunctionRole.Arn
      KmsKeyArn: !GetAtt DCSSDataKMSKey.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DcssTable
          HASH_KEY: !Sub ${HashKey}

  StatusAPIFunctionGatewayPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt StatusAPIFunction.Arn
        Principal: apigateway.amazonaws.com
        SourceArn: !Join [ "", [ "arn:aws:execute-api:", !Sub "${AWS::Region}:", !Sub "${AWS::AccountId}:", !Ref StatusAPI, "/*"] ]

  #ACTION TAKEN

  ActionTakenFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub dcss-${Environment}-action-taken-func
      Handler: src/api/action-taken.handler
      Runtime: nodejs6.10
      Code: ./
      Role: !GetAtt ActionTakenFunctionRole.Arn
      KmsKeyArn: !GetAtt DCSSDataKMSKey.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref DcssTable
          ACTION_TABLE_NAME: !Ref ActionTakenTable
          HASH_KEY: !Sub ${HashKey}
          KEY_ALIAS: !Ref DCSSDataKMSKeyAlias

  ActionTakenFunctionGatewayPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt ActionTakenFunction.Arn
        Principal: apigateway.amazonaws.com
        SourceArn: !Join [ "", [ "arn:aws:execute-api:", !Sub "${AWS::Region}:", !Sub "${AWS::AccountId}:", !Ref ActionTakenAPI, "/*"] ]

###################################### API GATEWAY #####################################################################

  #STATUS

  StatusAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub dcss-${Environment}-status-api
      Description: "API used to return participant status"
      EndpointConfiguration:
        Types:
          - REGIONAL

  StatusAPIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref StatusAPIDeployment
      RestApiId: !Ref StatusAPI
      StageName: !Sub ${Environment}

  StatusAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: StatusAPIRequest
    Properties:
      RestApiId: !Ref StatusAPI

  StatusAPIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref StatusAPI
      ParentId: !GetAtt StatusAPI.RootResourceId
      PathPart: status

  StatusAPIRequest:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      RestApiId: !Ref StatusAPI
      ResourceId: !Ref StatusAPIResource
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StatusAPIFunction.Arn}/invocations

  #ACTION TAKEN

  ActionTakenAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub dcss-${Environment}-action-taken-api
      Description: "API used to post license action taken"
      EndpointConfiguration:
        Types:
          - REGIONAL

  ActionTakenAPIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ActionTakenAPIDeployment
      RestApiId: !Ref ActionTakenAPI
      StageName: !Sub ${Environment}

  ActionTakenAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ActionTakenAPIRequest
    Properties:
      RestApiId: !Ref ActionTakenAPI

  ActionTakenAPIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ActionTakenAPI
      ParentId: !GetAtt ActionTakenAPI.RootResourceId
      PathPart: action-taken

  ActionTakenAPIRequest:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      RestApiId: !Ref ActionTakenAPI
      ResourceId: !Ref ActionTakenAPIResource
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ActionTakenFunction.Arn}/invocations

###################################### DYNAMODB ########################################################################

  #DCSS TABLE

  DcssTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: ssnHash
            AttributeType: S
          - AttributeName: stateIdHash
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          -
            IndexName: !Sub ssnHash-index
            KeySchema:
              -
                AttributeName: ssnHash
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          -
            IndexName: !Sub stateIdHash-index
            KeySchema:
              -
                AttributeName: stateIdHash
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

  #ACTION TAKEN
  ActionTakenTable:
        Type: AWS::DynamoDB::Table
        Properties:
          AttributeDefinitions:
            - AttributeName: agencyCustomerId
              AttributeType: S
            - AttributeName: timestamp
              AttributeType: S
            - AttributeName: actionTakenDate
              AttributeType: S
            - AttributeName: actionTakenMonthYear
              AttributeType: S
          KeySchema:
            - AttributeName: agencyCustomerId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          GlobalSecondaryIndexes:
            -
              IndexName: !Sub actionTakenDate-index
              KeySchema:
                -
                  AttributeName: actionTakenDate
                  KeyType: HASH
              Projection:
                ProjectionType: ALL
              ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
            -
              IndexName: !Sub actionTakenMonthYear-index
              KeySchema:
                -
                  AttributeName: actionTakenMonthYear
                  KeyType: HASH
              Projection:
                ProjectionType: ALL
              ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

###################################### S3 BUCKETS AND EVENTS ###########################################################

  DelinquencyImportBucket:
      Type: AWS::S3::Bucket
      DependsOn: DelinquencyImportFunctionS3Permission
      Properties:
        AccessControl: AuthenticatedRead
        BucketName:  !Sub dcss-${Environment}-delinquency-import-bucket
        NotificationConfiguration:
              LambdaConfigurations:
                -
                  Function: !GetAtt DelinquencyImportFunction.Arn
                  Event: "s3:ObjectCreated:*"

###################################### ROLES AND POLICIES ##############################################################

  DelinquencyImportFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole

  StatusAPIFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole

  ActionTakenFunctionRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Principal:
                  Service:
                    - lambda.amazonaws.com
                Action:
                  - sts:AssumeRole

  #common re-usable policies

  ReadDataOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ReadDataOnlyPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
          -
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:BatchGetItem
            Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/dcss-dev-*
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/dcss-test-*
      Roles:
        - !Ref StatusAPIFunctionRole


  UpdateDataPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ReadDataOnlyPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
          -
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:BatchWriteItem
              - dynamodb:BatchGetItem
            Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/dcss-dev-*
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/dcss-test-*
      Roles:
        - !Ref ActionTakenFunctionRole

  LambdaImportPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaImportPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
          -
            Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:BatchWriteItem
              - dynamodb:BatchGetItem
            Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/dcss-dev-*
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/dcss-test-*
          -
            Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - arn:aws:s3:::dcss-test-*
              - arn:aws:s3:::dcss-dev-*
      Roles:
        - !Ref DelinquencyImportFunctionRole

###################################### KMS #############################################################################

  DCSSDataKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: 'Master key for dcss envelope data encryption'
      KeyPolicy:
          Version: "2012-10-17"
          Id: !Sub ${AWS::StackName}-DCSSDataKeyPolicy
          Statement:
            - Sid: "Allow administration of the key only to root"
              Effect: Allow
              Principal:
                #AWS: arn:aws:iam::AccountId:root
                AWS:
                  - !Join [ "", [ "arn:aws:iam::", !Ref "AWS::AccountId", ":root" ] ]
                  - !Join [ "", [ "arn:aws:iam::", !Ref "AWS::AccountId", ":user/dcss-dev" ] ]
              Resource: "*"
              Action: kms:*
            - Sid: "Allow access to encrypt/decrypt abilities to the lambda functions"
              Effect: Allow
              Principal:
                AWS:
                  - !GetAtt DelinquencyImportFunctionRole.Arn
                  - !GetAtt StatusAPIFunctionRole.Arn
                  - !GetAtt ActionTakenFunctionRole.Arn
              Action:
                - kms:Encrypt
                - kms:Decrypt
                - kms:GenerateDataKey*
              Resource: "*"

  DCSSDataKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/dcss-${Environment}-key
      TargetKeyId:
        Ref: DCSSDataKMSKey


